language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

gemfile:
 - Gemfile

branches:
  only:
    - master

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
